package com.uart.entitylib.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.uart.entitylib.entity.SysConfig;
import com.uart.entitylib.entity.SysConfigVersion;

import com.uart.entitylib.dao.SysConfigDao;
import com.uart.entitylib.dao.SysConfigVersionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sysConfigDaoConfig;
    private final DaoConfig sysConfigVersionDaoConfig;

    private final SysConfigDao sysConfigDao;
    private final SysConfigVersionDao sysConfigVersionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sysConfigDaoConfig = daoConfigMap.get(SysConfigDao.class).clone();
        sysConfigDaoConfig.initIdentityScope(type);

        sysConfigVersionDaoConfig = daoConfigMap.get(SysConfigVersionDao.class).clone();
        sysConfigVersionDaoConfig.initIdentityScope(type);

        sysConfigDao = new SysConfigDao(sysConfigDaoConfig, this);
        sysConfigVersionDao = new SysConfigVersionDao(sysConfigVersionDaoConfig, this);

        registerDao(SysConfig.class, sysConfigDao);
        registerDao(SysConfigVersion.class, sysConfigVersionDao);
    }
    
    public void clear() {
        sysConfigDaoConfig.clearIdentityScope();
        sysConfigVersionDaoConfig.clearIdentityScope();
    }

    public SysConfigDao getSysConfigDao() {
        return sysConfigDao;
    }

    public SysConfigVersionDao getSysConfigVersionDao() {
        return sysConfigVersionDao;
    }

}
